In [1]:
import numpy as np  #Importar libreria

### Crear arreglos

In [18]:
vector=np.array([1,2,3,4,5]) #Crear vector desde una lista 
matriz = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
escalar=np.array(1) #Crear escalar
print('Matriz manual:\n',matriz)

#Crear vector por secuencia (segun intervalos)
vec_sec1=np.arange(1,10,2) #Parametros: start, finish, step
print('Vector desde secuencia (intervalo definido):',vec_sec1)

#Crear vector por secuencia (segun cantidad deseada)
vec_sec2=np.linspace(1,0,18) 
print('Vector desde secuencia (cantidad definida):',vec_sec2)

Matriz manual:
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Vector desde secuencia (intervalo definido): [1 3 5 7 9]
Vector desde secuencia (cantidad definida): [1.         0.94117647 0.88235294 0.82352941 0.76470588 0.70588235
 0.64705882 0.58823529 0.52941176 0.47058824 0.41176471 0.35294118
 0.29411765 0.23529412 0.17647059 0.11764706 0.05882353 0.        ]


In [6]:
#Vectores y matrices de ceros (datos son float)
vec_z=np.zeros(5)
print('Vector de ceros:\n',vec_z)
mat_z=np.zeros((2,3))
print('Matriz de ceros:\n',mat_z)

#Vectores y matrices de unos (datos son float)
vec_1=np.ones(5)
print('Vector de ceros:\n',vec_1)
mat_1=np.ones((2,3))
print('Matriz de ceros:\n',mat_1)

#Vectores y matrices de un mismo valor 
mat_u=np.full(shape=(2,3),fill_value=5) #int
print('Matriz de un mismo valor (int):\n',mat_u)

mat_str=np.full(shape=(2,3),fill_value='s') #str
print('Matriz de un mismo valor (str):\n',mat_str)

mat_b=np.full(shape=(2,3),fill_value=True) #bool
print('Matriz de un mismo valor (bool):\n',mat_b)

Vector de ceros:
 [0. 0. 0. 0. 0.]
Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Vector de ceros:
 [1. 1. 1. 1. 1.]
Matriz de ceros:
 [[1. 1. 1.]
 [1. 1. 1.]]
Matriz de un mismo valor (int):
 [[5 5 5]
 [5 5 5]]
Matriz de un mismo valor (str):
 [['s' 's' 's']
 ['s' 's' 's']]
Matriz de un mismo valor (bool):
 [[ True  True  True]
 [ True  True  True]]


In [7]:
#Matrices con valores random

#Crear matriz random entre 0 y 1
matriz1=np.random.rand(2,3)
print('matriz random\n',matriz1)

#Crear matriz random distribucion normal estandar
matriz2=np.random.randn(2,3) 
print('matriz distribucion normal estandar (media=0 desviacion=1)\n',matriz2)

#Crear matriz random de enteros
matriz3=np.random.randint(2,8,size=(2,3)) 
print('matriz random enteros\n',matriz3)

#Crear matriz random segun diatribucion uniforme
matriz4=np.random.uniform(low=2,high=8,size=(2,3)) 
print('matriz distribucion uniforme (l=2 h=8)\n',matriz4)

#Crear matriz random segun distribucion normal
matriz5=np.random.normal(loc=3,scale=2,size=(2,3)) 
print('matriz distribucion normal (media=3 desviacion=2)\n',matriz5)

matriz random
 [[0.37529893 0.17564512 0.13028427]
 [0.44952071 0.67849832 0.76851749]]
matriz distribucion normal estandar (media=0 desviacion=1)
 [[-0.31625477 -0.07656806  1.86196494]
 [ 0.80944436 -0.40740828  0.76855514]]
matriz random enteros
 [[6 4 4]
 [6 5 7]]
matriz distribucion uniforme (l=2 h=8)
 [[2.20488968 4.20673826 7.34199466]
 [6.41156595 2.6065023  7.75838477]]
matriz distribucion normal (media=3 desviacion=2)
 [[1.66567132 3.17107818 3.37274922]
 [3.43957259 2.0263237  3.46657991]]


### Modificar arreglos

In [9]:
#Cambiar dimensiones de una matriz 
#Se debe mantener la misma cantidad de datos

m_original=np.random.randint(2,8,size=(4,2)) 
print('matriz original\n',m_original)

m_reshaped=m_original.reshape([4,2])
print('matriz cambiada\n',m_reshaped)

#Se puede volver vector o tensor
vec=m_original.reshape([1,8])
print('vector\n',vec)

tensor=m_original.reshape([2,2,2])
print('tensor\n',tensor)


matriz original
 [[6 7]
 [6 2]
 [2 7]
 [6 5]]
matriz cambiada
 [[6 7]
 [6 2]
 [2 7]
 [6 5]]
vector
 [[6 7 6 2 2 7 6 5]]
tensor
 [[[6 7]
  [6 2]]

 [[2 7]
  [6 5]]]


In [27]:
#Asignar valores
arr3=np.zeros([3,5])
print(arr3)

#Valor especifico
arr3=np.zeros([3,5])
arr3[1,3] = 5 
print('modificacion 1 (un solo valor)\n',arr3)

#Filas enteras
arr3=np.zeros([3,5])
arr3[2,:] = 1 
print('modificacion 2 (una fila entera)\n',arr3)

#Columnas enteras
arr3=np.zeros([3,5])
arr3[:,4] = 2
print('modificacion 3 (una columna entera)\n',arr3)

#Varios valores a la vez
arr3=np.zeros([3,5])
arr3[[0,2],[1,4]] = 1 #Se modifica el (0,1) y el (2,4)
print('modificacion a (varios valores a la vez)\n',arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
modificacion 1 (un solo valor)
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0.]]
modificacion 2 (una fila entera)
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
modificacion 3 (una columna entera)
 [[0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 2.]]
modificacion a (varios valores a la vez)
 [[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


### Copiar arreglos

In [43]:
#Si se copia solo con '=' (shallow copy) los arreglos siguen vinculados
m=np.arange(10,30)
print('Arreglo original - Antes\n',m)
m1=m
print('Copia - Antes\n',m1)

#Si se modifica un valor en una, se modifica en la otra
m1[2]=999
print('Arreglo original - Despues\n',m)
print('Copia - Despues\n',m1)

Arreglo original - Antes
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Copia - Antes
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Arreglo original - Despues
 [ 10  11 999  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29]
Copia - Despues
 [ 10  11 999  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29]


In [44]:
#Para copiar arreglo (deep copy)
m=np.arange(10,30)
print('Arreglo original - Antes\n',m)
m1=m.copy()
print('Copia - Antes\n',m)
m1[2]=999
print('Arreglo original - Despues\n',m)
print('Copia - Despues\n',m1)

Arreglo original - Antes
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Copia - Antes
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Arreglo original - Despues
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Copia - Despues
 [ 10  11 999  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29]


### Slicing arrays

In [6]:
arr3=np.random.randint(1,17,(6,6))
print(arr3,'type:',type(arr3))

#Tomar un solo valor
sl_v=arr3[5,5] #Toma el (4,5)
print('Slice columna completa:\n',sl_v,'type:',type(sl_v))

#Tomar algunos valores
sl_vs=arr3[[1,2],[1,2]] #Toma el (1,1) y el (2,2)
print('Slice columna completa:\n',sl_vs,'shape: ',sl_vs.shape)

#Tomar una fila commpleta
sl_f=arr3[3,:]
print('Slice fila completa:\n',sl_f,'shape: ',sl_f.shape)

#Tomar una columna completa
sl_c=arr3[:,3]
print('Slice columna completa:\n',sl_c,'shape: ',sl_c.shape)

#Tomar una sub matriz de filas/columnas
sl_fs1=arr3[3:,2:] #Toma de la fila 4 en adelante y de la columna 3 en adelante
print('Sub matriz de n en adelante:\n',sl_fs1,'shape: ',sl_fs1.shape,'type:',type(sl_fs1))

#Tomar una sub matriz de rango de filas/columnas
sl_fs2=arr3[3:5,0:4] #Toma de la fila 4 y 5 y de la columna 0 a la 4 
#Para coger la ultima f/c se debe usar el numero +1 
#Ejemplo: Coger columna 5 (posicion 4 en matriz) hay que usar el 5
print('Sub matriz de rango de filas/columnas:\n',sl_fs2,'shape: ',sl_fs2.shape,'type:',type(sl_fs2))


[[ 4  6  7 12  1  9]
 [ 2  1 12  4  4 15]
 [14 15  8  9  9 13]
 [ 2  7  3 14 10  8]
 [ 5 14 14 13  9  8]
 [11 14  3 13  1 11]] type: <class 'numpy.ndarray'>
Slice columna completa:
 11 type: <class 'numpy.int32'>
Slice columna completa:
 [1 8] shape:  (2,)
Slice fila completa:
 [ 2  7  3 14 10  8] shape:  (6,)
Slice columna completa:
 [12  4  9 14 13 13] shape:  (6,)
Sub matriz de n en adelante:
 [[ 3 14 10  8]
 [14 13  9  8]
 [ 3 13  1 11]] shape:  (3, 4) type: <class 'numpy.ndarray'>
Sub matriz de rango de filas/columnas:
 [[ 2  7  3 14]
 [ 5 14 14 13]] shape:  (2, 4) type: <class 'numpy.ndarray'>


### Identificar tamaño

In [13]:
#Tamaño de los arreglos

print('Tamaño matriz original:',m_original.shape)
print('Tamaño matriz modificada:',m_reshaped.shape)
print('Tamaño vector:',vec.shape)
print('Tamaño tensor:',tensor.shape)

Tamaño matriz original: (4, 2)
Tamaño matriz modificada: (4, 2)
Tamaño vector: (1, 8)
Tamaño tensor: (2, 2, 2)


### Operaciones aritmeticas (valor por valor)

In [84]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
print(a1,'\ntamano',a1.shape)
a2 = np.array([[1,2,3,4],[5,6,7,8]])
print(a2,'\ntamano',a2.shape)

#Multiplicar 2 matrices valor por valor / Division igual
a3 = a1 / a2
print('\n matriz prducto\n',a3,'\ntamano',a3.shape)

#Sumar 2 matrices valor por valor / Resta igual
a3 = a1 + a2 
print('\n matriz suma\n',a3,'\ntamano',a3.shape)

#Lo mismo para hacer operaciones con constantes
a3 = a1 / 3
print(a3)


[[1 2 3 4]
 [5 6 7 8]] 
tamano (2, 4)
[[1 2 3 4]
 [5 6 7 8]] 
tamano (2, 4)

 matriz prducto
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
tamano (2, 4)

 matriz suma
 [[ 2  4  6  8]
 [10 12 14 16]] 
tamano (2, 4)
[[0.33333333 0.66666667 1.         1.33333333]
 [1.66666667 2.         2.33333333 2.66666667]]


### Operaciones matriciales

In [81]:
#Trasponer vector
vec = np.array([[1,2,3,4,5,6]])
tras_v = vec.T
print('Trasponer vector:\n',vec)
print(tras_v)

#Trasponer matriz
mat = np.array([[1,2,3,4],[5,6,7,8]])
tras_m=mat.T
print('Trasponer matriz:\n',mat)
print(tras_m)

Trasponer vector:
 [[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Trasponer matriz:
 [[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [90]:
#Multiplicacion matricial
#Debe coincidir las columnas de m1 (nxm) y las filas de m2 (mxp)
#El producto es de dimensiones (nxp) filas de m1 y columnas de m2

mat1 = np.array([[1,2],[4,1],[3,4],[1,1]]) #(4,2)
mat2 = np.array([[2,3,4],[1,2,3]]) #2,3)

mp = np.matmul(mat1,mat2) #(4,3)
print(mp)


[[ 4  7 10]
 [ 9 14 19]
 [10 17 24]
 [ 3  5  7]]


In [31]:
#Mascaras
m=np.arange(10,30)
print(m)

mask = ((m%3)==0) #Crea una matriz de booleans que evalua la condicion en cada valor

m[mask] #Toma todos los valores de la matriz que dieron True

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


array([12, 15, 18, 21, 24, 27])

### Estadistica

In [94]:
info = np.random.randint(70,80,(1,26))

print(info)
print(np.mean(info)) #promedio
print(np.median(info)) #moda
print(np.std(info)) #desviacion estandar
print(np.percentile(info,90)) #percentil 90

[[78 78 76 76 71 79 78 78 78 79 73 70 73 70 77 70 79 72 70 78 72 78 78 75
  73 75]]
75.15384615384616
76.0
3.230769230769231
78.5


In [101]:
a = np.arange(4) #4 primeros numeros 
b = np.arange(1,5) #todos los enteros en el rango 

print(a)
print(b)

display(np.exp(a)) #exponencial
display(np.log(a)) #logaritmo natural
display(np.sqrt(a)) #raiz cuadrada
display(np.greater(a,b)) #superior o igual punto a punto

[0 1 2 3]
[1 2 3 4]


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11504\3204165181.py:8: RuntimeWarning: divide by zero encountered in log
  display(np.log(a)) #logaritmo natural


array([      -inf, 0.        , 0.69314718, 1.09861229])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])