In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Crear Series

##### series=pd.Series(lista_datos,lista_indices)

In [2]:
#A partir de una lista
a=np.arange(1,10)
print(a)
s1=pd.Series(a)
print(s1)

s2=pd.Series([1,2,3,4,5,6,7,8,9])
#print(s2)

#Se puede crear con indices definidos directamente
s3 = pd.Series([1,2,3,4,5,6,7], index=['a', 'b', 'c', 'd','e','f','g']) #lista de str
print('Indice directo:\n',s3)

#Se puede crear con indices definidos desde listas
d3=[1,2,3,4,5,6,7]
i3=['g', 'f', 'e', 'd','c','b','a'] #lista de str
s3 = pd.Series(d3, i3) 
print('Indice desde lista:\n',s3)

s4 = pd.Series([1,2,3,4], index=[5,6,7,8]) #lista de int
print(s4)


[1 2 3 4 5 6 7 8 9]
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
Indice directo:
 a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64
Indice desde lista:
 g    1
f    2
e    3
d    4
c    5
b    6
a    7
dtype: int64
5    1
6    2
7    3
8    4
dtype: int64


In [3]:
#A partir de un diccionario

#Diccionario creado previamente
p_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

po = pd.Series(p_dict)
print(po)

print(po.values)
print(po.index) #Las llaves de vuelven los indices

#Diccionario directamente como parametro
po2=pd.Series({'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}) 
print(po2)

#Se puede crear una serie con una parte de un diccionario segun las llaves/indices
po3=pd.Series(p_dict,index=['California','Florida']) 
print(po3)


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
[38332521 26448193 19651127 19552860 12882135]
Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
California    38332521
Florida       19552860
dtype: int64


### Conocer info de la Serie

In [4]:
print(s1.values)
print('Info indice S1:',s1.index) #Info del indice de la serie
print('Info indice S3:',s3.index) #Info del indice de la serie

[1 2 3 4 5 6 7 8 9]
Info indice S1: RangeIndex(start=0, stop=9, step=1)
Info indice S3: Index(['g', 'f', 'e', 'd', 'c', 'b', 'a'], dtype='object')


### Tomar valores de la Serie

##### Con posicion: serie.iloc[]
##### Con indice: serie[]

In [5]:
print('Serie original:\n',s3)

#Tomar un valor con la posicion
v_s3_p=s3.iloc[1]
print(v_s3_p)

#Tomar un valor con el indice
v_s3_i=s3['b']
print('b',v_s3_i)

#Tomar valores a partir/desde de un punto
v=s3.iloc[2:] #Del 3 valor en adelante
print(v)

v=s3.iloc[:3] #Valores hasta la fila 3 (posicion 2)
print(v)

v=s3.iloc[3:-2] #Valores desde el 4 hasta antes de los ultimos dos (-2) valores
print(v)

Serie original:
 g    1
f    2
e    3
d    4
c    5
b    6
a    7
dtype: int64
2
b 6
e    3
d    4
c    5
b    6
a    7
dtype: int64
g    1
f    2
e    3
dtype: int64
d    4
c    5
dtype: int64


In [6]:
#Tomar por posicion
v=s3.iloc[3:6] #Valores desde el 4 hasta el 6 (posicion 5)
print('Toma con posicion:\n',v)

#Tomar por indice
v=s3['d':'f'] #Valores desde el 4 hasta el 6 (posicion 5)
print('Toma con indice:\n',v)


Toma con posicion:
 d    4
c    5
b    6
dtype: int64
Toma con indice:
 Series([], dtype: int64)


### Crear Data Frames
##### A partir de Series: df = pd.DataFrame( { 'Columna1' : serie1 ,'Columna2': serie2 } )
##### A partir de lista de Diccionarios
##### A partir de Matriz

In [7]:
#A partir de series
popu=pd.Series({'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}) 

area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': np.nan})

states = pd.DataFrame({'Population': popu,'Area': area})
states

Population      Area
California    38332521  423967.0
Texas         26448193  695662.0
New York      19651127  141297.0
Florida       19552860  170312.0
Illinois      12882135       NaN

In [23]:
#Si las series no tienen los mismos indices, se toman los indices de ambos y se rellena con NaN
area2 = pd.Series({'Washington': 423967, '  Michigan': 695662, 'Oregon': 141297,
             'Colorado': 170312, 'Arizona': np.nan})

states2 = pd.DataFrame({'Population': popu,'Area': area2})
states2


Population      Area
  Michigan         NaN  695662.0
Arizona            NaN       NaN
California  38332521.0       NaN
Colorado           NaN  170312.0
Florida     19552860.0       NaN
Illinois    12882135.0       NaN
New York    19651127.0       NaN
Oregon             NaN  141297.0
Texas       26448193.0       NaN
Washington         NaN  423967.0

In [28]:
states2.isnull().sum()

Population    5
Area          6
dtype: int64

In [9]:
#A partir de una lista de diccionarios
a=[{'a': i, 'b': i/2+6} for i in range(10)]
print(a)

df1=pd.DataFrame(a)
df1

[{'a': 0, 'b': 6.0}, {'a': 1, 'b': 6.5}, {'a': 2, 'b': 7.0}, {'a': 3, 'b': 7.5}, {'a': 4, 'b': 8.0}, {'a': 5, 'b': 8.5}, {'a': 6, 'b': 9.0}, {'a': 7, 'b': 9.5}, {'a': 8, 'b': 10.0}, {'a': 9, 'b': 10.5}]


a     b
0  0   6.0
1  1   6.5
2  2   7.0
3  3   7.5
4  4   8.0
5  5   8.5
6  6   9.0
7  7   9.5
8  8  10.0
9  9  10.5

In [10]:
#Usando una matriz (array)
b=np.array([[1,2],[3,4],[5,6]])
print(b)
df2=pd.DataFrame(b,
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

df2

[[1 2]
 [3 4]
 [5 6]]


foo  bar
a    1    2
b    3    4
c    5    6

### Conocer info de Data Frame

In [11]:
print('Indices:',states.index) #Indices
print('Columnas:',states.columns) #Columnas 

Indices: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Columnas: Index(['Population', 'Area'], dtype='object')


### Tomar valores de Data Frame

In [12]:
#Tomar los valores de una columna con indice
c_area=states['Area']
print(c_area)

#Tomar columnas completas con posicion
c1=states.iloc[:, 1] # Segunda columna
c2=states.iloc[:, -1] # Última columna

print('Segunda columna:\n',c1)
print('Ultima columna:\n',c2)

California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois           NaN
Name: Area, dtype: float64
Segunda columna:
 California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois           NaN
Name: Area, dtype: float64
Ultima columna:
 California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois           NaN
Name: Area, dtype: float64


In [13]:
#Tomar toda una fila: La informacion de un indice
f1=states.iloc[1,:] 
print('Segunda fila:\n',f1)

Segunda fila:
 Population    26448193.0
Area            695662.0
Name: Texas, dtype: float64


### Modificar valores en Data Frame

In [14]:
#Cambiar los valores de un indice (fila)
x = pd.DataFrame({'x': [1, 2, 3], 'y': [3, 4, 5]})
print('Antes:\n',x)
x.iloc[1] = {'x': 9, 'y': 99}
print('Despues cambio fila:\n',x)

#Para cambiar una columna
x['x']=[7,8,9]
print('Despues cambio columna:\n',x)

#Si los indices no son compatibles se borran los datos
n=x.copy()
n.iloc[1] = {'a': 9, 'c': 99} 
print('Despues indices equivocados:\n',n)

#Si el indice no existe se agrega una columna
m=x.copy()
m['a']=[10,12,13]
print(m)

#Para modificar el indice de una fila
m.rename(index={1:'uno'},inplace=True) #inplace hace que se modifique el mismo DataFrame
print(m)


Antes:
    x  y
0  1  3
1  2  4
2  3  5
Despues cambio fila:
    x   y
0  1   3
1  9  99
2  3   5
Despues cambio columna:
    x   y
0  7   3
1  8  99
2  9   5
Despues indices equivocados:
      x    y
0  7.0  3.0
1  NaN  NaN
2  9.0  5.0
   x   y   a
0  7   3  10
1  8  99  12
2  9   5  13
     x   y   a
0    7   3  10
uno  8  99  12
2    9   5  13


### Borrar filas/columnas

In [15]:
#Borrar fila con posicion
m=m.drop(2)
m

x   y   a
0    7   3  10
uno  8  99  12

In [16]:
#Borrar columna con indice
m.drop(columns='x')

y   a
0     3  10
uno  99  12

In [20]:
#Borra filas con NaN
states.dropna(inplace=True)
states

Population      Area     Density
California    38332521  423967.0   90.413926
Texas         26448193  695662.0   38.018740
New York      19651127  141297.0  139.076746
Florida       19552860  170312.0  114.806121

### Operaciones

In [21]:
#Se pueden hacer operaciones entre columnas y guardar en columna nueva

states['Density']=states['Population']/states['Area']
states

Population      Area     Density
California    38332521  423967.0   90.413926
Texas         26448193  695662.0   38.018740
New York      19651127  141297.0  139.076746
Florida       19552860  170312.0  114.806121